import React from "react";

const Tabla1 = () => {
  return (
    <div>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Tabla del 1</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th>1</th>
            <td>x</td>
            <td>1</td>
            <td>=</td>
            <td>1</td>
          </tr>
          <tr>
            <th>1</th>
            <td>x</td>
            <td>2</td>
            <td>=</td>
            <td>2</td>
          </tr>
          <tr>
            <th>1</th>
            <td>x</td>
            <td>3</td>
            <td>=</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>x</td>
            <td>4</td>
            <td>=</td>
            <td>4</td>
          </tr>
          <tr>
            <th>1</th>
            <td>x</td>
            <td>5</td>
            <td>=</td>
            <td>5</td>
          </tr>
          <tr>
            <th>1</th>
            <td>x</td>
            <td>6</td>
            <td>=</td>
            <td>6</td>
          </tr>
          <tr>
            <th>1</th>
            <td>x</td>
            <td>7</td>
            <td>=</td>
            <td>7</td>
          </tr>
          <tr>
            <th>1</th>
            <td>x</td>
            <td>8</td>
            <td>=</td>
            <td>8</td>
          </tr>
          <tr>
            <th>1</th>
            <td>x</td>
            <td>9</td>
            <td>=</td>
            <td>9</td>
          </tr>
          <tr>
            <th>1</th>
            <td>x</td>
            <td>10</td>
            <td>=</td>
            <td>10</td>
          </tr>
        </tbody>
      </table>
    </div>
  );
};

export default Tabla1;
